name: Stage deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  SFTP_PATH: ${{ secrets.STAGE_PATH }}

jobs:
  stage-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Deploy Files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PEM_KEY }}
          REMOTE_HOST: ${{ secrets.SFTP_SERVER }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          REMOTE_PORT: ${{ secrets.SFTP_PORT }}
          TARGET: ${{ env.SFTP_PATH }}
          EXCLUDE: "/.git/, /.github/"
          SCRIPT_BEFORE: rm -rf ${{ env.SFTP_PATH }}/*

      - name: Run Docker
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PEM_KEY }}
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd ${{ env.SFTP_PATH }}
            docker rmi ai-front-app -f
            docker build -t ai-front-app .
            docker ps -q --filter "name=ai-front-app" | grep -q . && docker stop ai-front-app
            docker container prune -f
            docker run -d --name ai-front-app --restart always -p 8080:80 ai-front-app
            docker images -q --filter "dangling=true" | xargs docker rmi

      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.name }}

      - name: Commit Updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update version and CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
