name: Stage deploy

on:
  release:
    types:
      - released
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  SFTP_PATH: ${{ secrets.STAGE_PATH }}

jobs:
  stage-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PEM_KEY }}
          REMOTE_HOST: ${{ secrets.SFTP_SERVER }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          REMOTE_PORT: ${{ secrets.SFTP_PORT }}
          TARGET: ${{ env.SFTP_PATH }}
          EXCLUDE: "/.git/, /.github/"
          SCRIPT_BEFORE: rm -rf ${{ env.SFTP_PATH }}/*

      - name: Run Docker
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PEM_KEY }}
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd ${{ env.SFTP_PATH }}
            docker rmi ai-front-app -f
            docker build -t ai-front-app .
            docker ps -q --filter "name=ai-front-app" | grep -q . && docker stop ai-front-app
            docker container prune -f
            docker run -d --name ai-front-app -p 80:80 ai-front-app
